# The code that follows was almost completely generated by GPT-4 following my prompts.

import re
import numpy as np
import matplotlib.ticker as ticker
import matplotlib.pyplot as plt
from scripts.utils import truncate
from matplotlib.transforms import offset_copy

def save_occurrences(articles_df, regex_list, file):
    # create a copy of the dataframe
    df = articles_df[['author','year','title','doi']]
    # Find the occurrences of each regex in the text files
    for regex in regex_list:
        regex_occurrences = []
        for text in articles_df['text']:
            regex_occurrences.append(len(re.findall(regex, text)))
        df[regex] = regex_occurrences
    df = df[~(df[regex_list] == 0).all(axis=1)]
    df.to_excel(file, index=False)

def plot_occurrences(articles_df, regex_list, first_year=None, last_year=None,
                     add_article_list=False,
                     x_label=None, y_label=None, title=None,
                     figsize=None, plot_style="default", bar_color_palette="tab20", fontsize=12):

    plt.style.use(plot_style)

    # default size
    if figsize is None:
        figsize = (16, 10)

    # Find the occurrences of each regex in the text files
    for regex in regex_list:
        regex_occurrences = []
        for text in articles_df['text']:
            regex_occurrences.append(len(re.findall(regex, text)))
        articles_df[regex] = regex_occurrences

    # Group the occurrences by year
    grouped_occurrences = articles_df.groupby('year').agg({regex: sum for regex in regex_list})

    # Find the article with the most occurrences of the first regex in each year
    first_regex = regex_list[0]
    top_articles = articles_df.loc[articles_df.groupby('year')[first_regex].idxmax()]
    top_articles = top_articles.loc[top_articles[first_regex] > 0]
    if first_year is not None:
        top_articles = top_articles.loc[top_articles['year'] >= first_year]
    if last_year is not None:
        top_articles = top_articles.loc[top_articles['year'] <= last_year]
    top_articles = top_articles.reset_index(drop=True)

    years = grouped_occurrences.index
    n_years = len(years)
    bar_width = 0.8 / len(regex_list)

    if add_article_list:
        fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=figsize, gridspec_kw={'width_ratios': [3, 1]})
    else:
        fig, ax1 = plt.subplots(figsize=figsize)

    for idx, regex in enumerate(regex_list):
        x = np.arange(n_years) + idx * bar_width
        y = grouped_occurrences[regex]

        # color the bars
        if bar_color_palette == "monochrome":
            edgecolor = 'black'
            color = 'black' if idx == 0 else 'none'
        else:
            edgecolor = None
            color = getattr(plt.cm, bar_color_palette)(idx)
        bars = ax1.bar(x, y, width=bar_width, label=regex, color=color, edgecolor=edgecolor)

        # Add number on top of the first bar chart with consistent padding
        if idx == 0:
            for bar in bars:
                height = bar.get_height()
                if height > 0:
                    # Use offset_copy to make the offset in pixels, ensuring consistent padding
                    trans = offset_copy(ax1.transData, fig=fig, y=3, units='dots')
                    ax1.text(bar.get_x() + bar.get_width() / 2, height, str(height), fontsize=10,
                             ha='center', va='bottom', transform=trans)

    ax1.set_xticks(np.arange(n_years))
    ax1.set_xticklabels(years)
    ax1.xaxis.set_major_locator(ticker.MultipleLocator(base=5))
    ax1.xaxis.set_minor_locator(ticker.MultipleLocator(base=1))
    ax1.grid(axis='x', which='minor', linestyle=':', alpha=0.5)

    # add some padding to the y-axis do that the bar labels aren't cut off
    ymin, ymax = ax1.get_ylim()
    padding = (ymax - ymin) * 0.05
    ax1.set_ylim(ymin, ymax + padding)

    # Title, labels and legend
    if x_label:
        ax1.set_xlabel(x_label, fontsize=fontsize)
    if y_label:
        ax1.set_ylabel(y_label, fontsize=fontsize)
    if title is not None:
        plt.title(title)
    ax1.legend(fontsize=fontsize)

    # Create the box with the numbered list of top articles
    if add_article_list:
        top_articles_list = [
            f'{i+1}. {row["author"]} ({row["year"]}) {truncate(row["title"], 30)} [{row[first_regex]}]'
            for i, row in top_articles.iterrows()
        ]
        ax2.axis('off')
        for i, text in enumerate(top_articles_list):
            ax2.text(0, 1 - i * 0.05, text, fontsize=10, verticalalignment='top')

    plt.tight_layout()
    return plt
